disabled = false
languageCode = 'el-EL'
languageName = 'Ελληνικα'
title = 'Αικατερίνη Πομπόρτση'
copyright = """Σχεδιασμένο με [Hugo](https://gohugo.io/) από την [Pomware Innovative Solutions LTD](https://pomwareltd.com/)\n
Με άδεια χρήσης [MIT](https://github.com/ololiuhqui/magnolia-free-hugo-theme/blob/main/LICENSE.md)\n
© Όλα τα δικαιώματα διατηρούνται από την POMWARE INNOVATIVE SOLUTIONS LTD"""
contentDir = "content/el"

[params]
  subtitle = "Σύγχρονη ελληνική ποίηση"

# PAGES

  [params.homepage]
    preTitle = "Δωρεάν θέμα Hugo"
    title = "Magnolia"
    intro = """
### «Η ελευθερία μας κάνει καλύτερους ανθρώπους και μας βοηθά να βελτιωνόμαστε πιο γρήγορα ως συλλογική ανθρωπότητα».
___

**Ένα απλό, πλήρως παραμετροποιήσιμο και πολυγλωσσικό θέμα Hugo, σχεδιασμένο για επαγγελματίες και μικρές επιχειρήσεις**.

Έφτιαξα αυτό το θέμα με γνώμονα την απλότητα: είναι μικρό και εύκολα **παραμετροποιήσιμο, responsive, modular και πολυγλωσσικό**. Παράλληλα αφήνει χώρο για πιο βαθιά παραμετροποίηση, καθώς χρησιμοποιεί **Bootstrap** και **SCSS**.

Εδώ είναι η [σελίδα GitHub του θέματος](https://github.com/ololiuhqui/magnolia-free-hugo-theme). Αν ψάχνεις περισσότερες λεπτομέρειες, ανατρέξε εκεί — και μην ξεχάσεις να αφήσεις ένα ⭐ στο repo!

Δες τι μπορεί να κάνει αυτό το θέμα στη σελίδα χαρακτηριστικών και ένα όμορφο παράδειγμα σελίδας επικοινωνίας παρακάτω.
        """
    mainButton = "Χαρακτηριστικά"
    mainButtonRef = "/caratteristiche"
    secondButton = "Επικοινωνία"
    secondButtonRef = "/contatti"

    blogTitle = "Ενδιαφέρουσες ιστορίες"
    blogButton = "Περισσότερες ιστορίες"

[params.office]
  title = "Γραφεία"
  description = "Αυτή η σελίδα μπορεί να παραμετροποιηθεί εύκολα προσθέτοντας έναν σύνδεσμο Google Maps για οδηγίες προς την τοποθεσία της επιχείρησης."
  buttonText = "Οδηγίες"
  buttonLink = "https://maps.app.goo.gl/LzsPzRkTYSZ8SF3y8"
  mapLink = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d382266.44569392945!2d-76.55832397784323!3d41.53770983690751!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c4d93a77484bbb%3A0xfff27920ab9bfae8!2sScranton%2C%20Pennsylvania%2C%20United%20States!5e0!3m2!1sel!2sel!4v1716459350324!5m2!1sel!2sel" # Google Maps embed link

[params.contacts]
  title = "Επικοινωνήστε μαζί μας!"
  formCallToAction = "Αυτή είναι μια ενδεικτική σελίδα επικοινωνίας· μπορείτε να λαμβάνετε απαντήσεις από φόρμες μέσω Formspree (δωρεάν)."
  socialCallToAction = "Μπορείτε να μας ακολουθήσετε στα παρακάτω social media!"
  [params.contacts.form]
    formspreeLink = "https://yourformspreelink.com"
    firstname = "Όνομα*"
    lastname = "Επώνυμο*"
    email = "E-mail*"
    phone = "Τηλέφωνο*"
    Inquiry = "Μήνυμα*"
    checkbox = " αποδέχομαι την επεξεργασία των δεδομένων μου σύμφωνα με τον νόμο*"
    submitBtn = "Αποστολή"

[params.services]
  title = "Χαρακτηριστικά"
  description = """Έφτιαξα αυτό το θέμα με γνώμονα την απλότητα: είναι μικρό και εύκολα παραμετροποιήσιμο, responsive, modular και πολυγλωσσικό. Παράλληλα αφήνει χώρο για πιο βαθιά παραμετροποίηση, καθώς χρησιμοποιεί Bootstrap και SCSS.
  Αυτή η σελίδα δείχνει επίσης ένα παράδειγμα του πώς μπορούν να αλλάξουν τα ονόματα των σελίδων του site: το site θα χρησιμοποιήσει το layout `services.html`, αλλά η σελίδα θα ονομάζεται "Χαρακτηριστικά" και ο σύνδεσμος θα χρησιμοποιεί το σχετικό permalink `/caratteristiche`."""
  [params.services.list]
    [params.services.list.0]
      title = "Προσαρμογή σε όλες τις συσκευές"
      description = "Το θέμα είναι πλήρως responsive και προβάλλεται άψογα σε κάθε μέγεθος οθόνης."
    [params.services.list.01]
      title = "Αρθρωτή δομή"
      description = "Κρύψτε ή εμφανίστε εύκολα ορισμένα στοιχεία μέσα από το αρχείο ρυθμίσεων."
    [params.services.list.02]
      title = "Πολυγλωσσικό"
      description = "Η προεπιλεγμένη γλώσσα περιεχομένου είναι τα Αγγλικά (μπορεί να αλλάξει), αλλά μπορείτε να προσθέσετε όσες γλώσσες θέλετε πολύ εύκολα· το θέμα περιλαμβάνει παράδειγμα και dropdown μενού για εύκολη εναλλαγή γλώσσας. Τα permalinks μπορούν να προσαρμοστούν ανά γλώσσα."
    [params.services.list.03]
      title = "Παραμετροποιήσιμο"
      description = "Το περιεχόμενο της σελίδας μπορεί να παραμετροποιηθεί μέσα από τα αρχεία ρυθμίσεων. Ορισμένες μεταβλητές μπορούν να αλλάξουν από τα αρχεία SCSS."
    [params.services.list.04]
      title = "Έτοιμο για SEO"
      description = "Κάθε σελίδα στο /content έχει *meta description* και μοναδικό *meta title* για καλύτερη και πιο εύκολη ευρετηρίαση. Το θέμα χρησιμοποιεί την εικόνα `static/img/meta-image` ως meta-image για Google, Meta και X."
    [params.services.list.05]
      title = "Ενσωματωμένο Google Analytics"
      description = "Βάλτε το Google Analytics tag σας στο αρχείο `config.toml` και θα είστε έτοιμοι να παρακολουθείτε εύκολα την απόδοση του site σας."
    [params.services.list.06]
      title = "Ενσωματωμένο Google Maps"
      description = "Η σελίδα επικοινωνίας μπορεί να παραμετροποιηθεί εύκολα με την προσθήκη ενός Google Maps link για οδηγίες προς την τοποθεσία της επιχείρησης."

[params.socials]
  enabled = true
  callToAction = "Συνδεθείτε μαζί μας στα social media >"
      [[params.socials.link]]
        name = "github"
        link = "https://github.com/PomWare"
      [[params.socials.link]]
        name = "linkedin"
        link = ""
      [[params.socials.link]]
        name = "whatsapp"
        link = ""

[params.schedules]
  enabledFooter = false
  enabledContacts = true
  title = "Ώρες λειτουργίας"
  [params.schedules.days]
    day1 = "Δευτέρα: 9:00 – 19:00"
    day2 = "Τρίτη: 9:00 – 19:00"
    day3 = "Τετάρτη: 9:00 – 19:00"
    day4 = "Πέμπτη: 9:00 – 19:00"
    day5 = "Παρασκευή: 9:00 – 19:00"
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription1 = "Κατευθείαν από την πόλη του Scranton"
  extraDescription2 = "ΑΦΜ: 0000000000"
  [params.footer.navigate]
    heading = "Πλοηγηση"
  [params.footer.contacts]
    enabled = true
    heading = "Επικοινωνια με POMWARE"
    address = "Λευκωσία Κύπρος & Θεσσαλονίκη Ελλάδα"
    mail = "pomwareltd@gmail.com"
    mail2 = "dundermifflinorders@fakemail.com"
    phone = "+30 6942612515"

[params.notfound]
  title = "404, η σελίδα δεν βρέθηκε"

[params.single] # για σελίδες άρθρων (ορατό μόνο αν εμφανίζονται posts)
  similarContent = "Παρόμοιο περιεχόμενο"
  toc = "Περιεχόμενα"

[menus]
  [[menus.main]]
    name = "Ποιηματα"
    pageRef = "poems"
    weight = 2
  [[menus.main]]
    name = "Βιβλια"
    pageRef = "books"
    weight = 3
  # [[menus.main]]
  #   name = "Η Ιστορια μου"
  #   pageRef = "pages/services"
  #   weight = 4

  # [[menus.main]]
  #   name = "Επικοινωνια"
  #   pageRef = "pages/contacts"
  #   weight = 5
